// Remove this line completely
// import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import { StoryblokProvider } from "../components/StoryblokProvider";
import { Tour } from "../components/Tour";
import { Page } from "../components/Page";
import {Hero} from "../components/Hero"
import { Grid } from "../components/Grid";
import { Feature } from "../components/Feature";
import { Testimonial } from "../components/Testimonial";
import { RecommendedTours } from "../components/RecommendedTours";
import { RecommendedTour } from "../components/RecommendedTour";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const cachedFetch = (input,init) =>{
  return fetch(input,{
    ...init,
    cache:process.env.NODE_ENV === "development" ? "no-store" :"force-cache"
  })
}

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  components: {
    tour: Tour,
    page:Page,
    hero:Hero,
    grid:Grid,
    feature:Feature,
    testimonial:Testimonial,
    recommended_tours:RecommendedTours,
    recommended_tour:RecommendedTour
  },
  apiOptions:{
    fetch:cachedFetch,
  }
});

export default function RootLayout({ children }) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <header>
            <nav className="container mx-auto px-4 w-full py-8 flex justify-between">
              <Link href={"/"}>Home</Link>
              <Link href={"/tours"}>Tours</Link>
            </nav>
          </header>
         {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}