
import { Inter } from "next/font/google";
import "./globals.css";
import { StoryblokProvider } from "@/components/StoryblokProvider";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata= { 
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body
          className={`${inter.className} bg-blue-50`}
        >
            <header>
             <nav className="container mx-auto px-4 w-full py-8 flex justify-between">
              <Link href={"/"}>Home</Link>
              <Link href={"/tours"}>Tours</Link>
            </nav>
          </header>
         {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}