import type { Metadata } from "next";
import StoryblokProvider from "./components/StoryblokProvider";
import "./globals.css";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import Page from "../app/components/Page";
import SecondaryBannerpage from "../app/components/SecondaryBannerpage";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

storyblokInit({
  accessToken: process.env.STORYBLOK_ACCESS_TOKEN,
  use: [apiPlugin],
   components: {
    page: Page,
    secondary_bannerpage: SecondaryBannerpage,
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body>
          <h1>Layout</h1>
          {children}
          </body>
      </html>
    </StoryblokProvider>
  );
}